services:
  postgres:
    image: db
    container_name: db
    build:
      context: ./
    volumes:
      - db-data:/var/lib/pgsql/data
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
